// Placeholder for Supabase generated types
// This file will be generated by running: supabase gen types typescript --local

export interface Database {
  public: {
    Tables: {
      users: {
        Row: {
          id: string
          created_at: string
          updated_at: string
          tenant_id: string
          email: string
          full_name: string
          role: string
          department: string | null
          phone: string | null
          is_active: boolean
        }
        Insert: {
          id?: string
          created_at?: string
          updated_at?: string
          tenant_id: string
          email: string
          full_name: string
          role: string
          department?: string | null
          phone?: string | null
          is_active?: boolean
        }
        Update: {
          id?: string
          created_at?: string
          updated_at?: string
          tenant_id?: string
          email?: string
          full_name?: string
          role?: string
          department?: string | null
          phone?: string | null
          is_active?: boolean
        }
      }
      assets: {
        Row: {
          id: string
          created_at: string
          updated_at: string
          tenant_id: string
          name: string
          description: string | null
          asset_number: string
          category: string
          location: string
          status: string
          purchase_date: string | null
          warranty_expiry: string | null
          cost: number | null
          manufacturer: string | null
          model: string | null
          serial_number: string | null
          parent_asset_id: string | null
          custom_fields: Record<string, any> | null
        }
        Insert: {
          id?: string
          created_at?: string
          updated_at?: string
          tenant_id: string
          name: string
          description?: string | null
          asset_number: string
          category: string
          location: string
          status: string
          purchase_date?: string | null
          warranty_expiry?: string | null
          cost?: number | null
          manufacturer?: string | null
          model?: string | null
          serial_number?: string | null
          parent_asset_id?: string | null
          custom_fields?: Record<string, any> | null
        }
        Update: {
          id?: string
          created_at?: string
          updated_at?: string
          tenant_id?: string
          name?: string
          description?: string | null
          asset_number?: string
          category?: string
          location?: string
          status?: string
          purchase_date?: string | null
          warranty_expiry?: string | null
          cost?: number | null
          manufacturer?: string | null
          model?: string | null
          serial_number?: string | null
          parent_asset_id?: string | null
          custom_fields?: Record<string, any> | null
        }
      }
      work_orders: {
        Row: {
          id: string
          created_at: string
          updated_at: string
          tenant_id: string
          title: string
          description: string
          work_order_number: string
          priority: string
          status: string
          type: string
          asset_id: string
          assigned_to: string | null
          requested_by: string
          due_date: string | null
          completed_at: string | null
          estimated_hours: number | null
          actual_hours: number | null
          cost: number | null
          notes: string | null
          custom_fields: Record<string, any> | null
        }
        Insert: {
          id?: string
          created_at?: string
          updated_at?: string
          tenant_id: string
          title: string
          description: string
          work_order_number: string
          priority: string
          status: string
          type: string
          asset_id: string
          assigned_to?: string | null
          requested_by: string
          due_date?: string | null
          completed_at?: string | null
          estimated_hours?: number | null
          actual_hours?: number | null
          cost?: number | null
          notes?: string | null
          custom_fields?: Record<string, any> | null
        }
        Update: {
          id?: string
          created_at?: string
          updated_at?: string
          tenant_id?: string
          title?: string
          description?: string
          work_order_number?: string
          priority?: string
          status?: string
          type?: string
          asset_id?: string
          assigned_to?: string | null
          requested_by?: string
          due_date?: string | null
          completed_at?: string | null
          estimated_hours?: number | null
          actual_hours?: number | null
          cost?: number | null
          notes?: string | null
          custom_fields?: Record<string, any> | null
        }
      }
    }
  }
}